#### Numpy Assignments

In [1]:
#1.How to concatenate two numpy arrays column-wise and row-wise?

import numpy as np
arr1 = np.ones((4,4))
arr2 = np.zeros((4,4))

#rowwise
print("rowise: \n\n {} \n\n".format(np.concatenate((arr1,arr2))))

#coloumnwise
print("coloumnwise: \n\n {}".format(np.concatenate((arr1,arr2),axis=1)))

rowise: 

 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 


coloumnwise: 

 [[1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]]


In [2]:
#2.Consider the random number generation functions in NumPy generate a set of random numbers using the function rand

np.random.rand(4,3)

array([[0.1653201 , 0.14283478, 0.51027799],
       [0.27183159, 0.64588057, 0.8751932 ],
       [0.54764515, 0.63499353, 0.14449935],
       [0.58633679, 0.42643628, 0.91518673]])

In [3]:
#3. Create a 3D array of shape 5x3x2 to contain random decimal numbers between 5 and 10

np.random.randint(5,10,size=(5,3,2))

array([[[8, 9],
        [5, 8],
        [6, 6]],

       [[5, 7],
        [9, 5],
        [5, 8]],

       [[8, 5],
        [7, 6],
        [9, 9]],

       [[9, 6],
        [7, 5],
        [9, 6]],

       [[9, 8],
        [8, 7],
        [5, 7]]])

In [4]:
#4.Create a utility function to generate random arrays using def random_array() takes number of elements as one 
#  of the argument, and randint() from random library. 
#Note: Do not use numpy function in this.

def random_array(n):
    return np.random.randint(999,size=n)
    
random_array(5)

array([628, 815, 823, 314, 155])

In [5]:
# 5.Create and Compute median using both Naive method using python only and Numpy function np.median()

def median_array(arr):
    arr.sort()
    size=len(arr)
    mid=int(size/2)
    if(size%2==0):
        return ((arr[mid]+arr[mid-1])/2)
    
    else:
        return (arr[mid])
    

temp=[1,2,10,7,5,4,88,55,0,77,54,33]   
print("Median using defied method: {}".format(median_array(temp)))
print("Median using NumPy: {}".format(np.median(temp)))

Median using defied method: 8.5
Median using NumPy: 8.5


In [6]:
#6.Create naive function to compute variance function, mean function using only python.

def mean(arr):
    return sum(arr)/len(arr)
  
def variance(arr): 
    avg=mean(arr)
    return sum(list(map(lambda x : (x-avg)**2 , arr)))/len(arr)
    

temp = [1,2,3,4,5,6]
print("Mean : {}" .format(mean(temp)))
print("Variance : {} " .format(variance(temp)))


Mean : 3.5
Variance : 2.9166666666666665 


In [7]:
#7 Convert a 1D array to a 2D array with 2 rows.
#    e.g. 
#    Input Array: ([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#    Output: [[0, 1, 2, 3, 4],
#     [5, 6, 7, 8, 9]]

arr=np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
if(len(arr)%2==0):
    print(arr.reshape(2,int(len(arr)/2)))
else:
    print("cannot split")

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [8]:
#8.How to stack two arrays vertically? Stack arrays A and B vertically?

A = np.random.randint(30,50,size=(4,4))
B = np.random.randint(20,size=(4,4))
np.vstack((A,B))

array([[44, 34, 45, 42],
       [40, 43, 40, 49],
       [43, 48, 48, 39],
       [46, 34, 46, 32],
       [10,  6,  1, 10],
       [ 8,  5, 17, 12],
       [ 0, 17,  3,  4],
       [ 1,  1, 14, 19]])

In [9]:
#9.Create a function using numpy to get the common items between two python numpy arrays?

A = np.random.randint(10,size=10)
B = np.random.randint(20,size=20)
np.intersect1d(A,B)

array([3, 6, 9])

In [10]:
#10.Create a python function to get the positions where elements of two arrays match using Numpy function?

arr1 = np.array([[1,20,30,2,3],[4,3,7,5,6]])
arr2 = np.array([[10,20,30,2,4],[5,6,7,8,6]])
np.argwhere(arr1==arr2)


array([[0, 1],
       [0, 2],
       [0, 3],
       [1, 2],
       [1, 4]], dtype=int64)

In [11]:
#11. How to create a 2D array containing random floats between 5 and 10?

(10-5)*np.random.ranf((5,3))+5

array([[8.21914615, 8.54115214, 9.45586231],
       [6.19400184, 8.0226404 , 5.20465437],
       [7.10448445, 7.73621865, 9.3330191 ],
       [8.12214874, 8.38409485, 5.5413374 ],
       [6.62202089, 5.1863742 , 5.32861913]])

In [12]:
#12. Extract the text column species from the 1D iris imported using following url np.genfromtxt()
# https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/iris.csv

iris_dataset=np.genfromtxt("https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/iris.csv",dtype="str",delimiter=",")

iris_dataset[1:,4]


array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [13]:
#13. How to Convert the 1D iris to 2D array iris_2d by omitting the species column and dropping first row?


iris_dataset=np.genfromtxt("https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/iris.csv",delimiter=",",usecols=(0,1,2,3),skip_header=1)
print(iris_dataset)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [14]:
#14. How to compute the mean, median, standard deviation of a numpy array on the same iris dataset?

iris_dataset.mean(axis = 0)

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [15]:
iris_dataset.std(axis=0)

array([0.82530129, 0.43441097, 1.75940407, 0.75969263])

In [16]:
np.median(iris_dataset,axis=0)

array([5.8 , 3.  , 4.35, 1.3 ])

In [17]:
#15. How to scale an array so the values range exactly between 0 and 1 using Admission.csv?
#    https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/Admission.csv
#    Change all the values in the range of 0-1.

admission_dataset=np.loadtxt("Admission.csv",delimiter=",",skiprows=1)
print(admission_dataset)

[[  1.   337.   118.   ...   9.65   1.     0.92]
 [  2.   324.   107.   ...   8.87   1.     0.76]
 [  3.   316.   104.   ...   8.     1.     0.72]
 ...
 [498.   330.   120.   ...   9.56   1.     0.93]
 [499.   312.   103.   ...   8.43   0.     0.73]
 [500.   327.   113.   ...   9.04   0.     0.84]]


In [18]:
(admission_dataset-np.min(admission_dataset,axis=0))/np.ptp(admission_dataset,axis=0)

array([[0.        , 0.94      , 0.92857143, ..., 0.91346154, 1.        ,
        0.92063492],
       [0.00200401, 0.68      , 0.53571429, ..., 0.66346154, 1.        ,
        0.66666667],
       [0.00400802, 0.52      , 0.42857143, ..., 0.38461538, 1.        ,
        0.6031746 ],
       ...,
       [0.99599198, 0.8       , 1.        , ..., 0.88461538, 1.        ,
        0.93650794],
       [0.99799599, 0.44      , 0.39285714, ..., 0.5224359 , 0.        ,
        0.61904762],
       [1.        , 0.74      , 0.75      , ..., 0.71794872, 0.        ,
        0.79365079]])

In [19]:
#16. Compute and Find the number and position of missing values in iris data’s sepal length column.
#    (And few missing values).

In [20]:
iris_dataset_temp = np.where(iris_dataset>5,np.nan,iris_dataset)
sepal_length_col= iris_dataset_temp[:,0]

#sepal_length_col
print("position:\n{} \n count:{} ".format(np.argwhere(np.isnan(sepal_length_col)),len((np.argwhere(np.isnan(sepal_length_col))))))

position:
[[  0]
 [  5]
 [ 10]
 [ 14]
 [ 15]
 [ 16]
 [ 17]
 [ 18]
 [ 19]
 [ 20]
 [ 21]
 [ 23]
 [ 27]
 [ 28]
 [ 31]
 [ 32]
 [ 33]
 [ 36]
 [ 39]
 [ 44]
 [ 46]
 [ 48]
 [ 50]
 [ 51]
 [ 52]
 [ 53]
 [ 54]
 [ 55]
 [ 56]
 [ 58]
 [ 59]
 [ 61]
 [ 62]
 [ 63]
 [ 64]
 [ 65]
 [ 66]
 [ 67]
 [ 68]
 [ 69]
 [ 70]
 [ 71]
 [ 72]
 [ 73]
 [ 74]
 [ 75]
 [ 76]
 [ 77]
 [ 78]
 [ 79]
 [ 80]
 [ 81]
 [ 82]
 [ 83]
 [ 84]
 [ 85]
 [ 86]
 [ 87]
 [ 88]
 [ 89]
 [ 90]
 [ 91]
 [ 92]
 [ 94]
 [ 95]
 [ 96]
 [ 97]
 [ 98]
 [ 99]
 [100]
 [101]
 [102]
 [103]
 [104]
 [105]
 [107]
 [108]
 [109]
 [110]
 [111]
 [112]
 [113]
 [114]
 [115]
 [116]
 [117]
 [118]
 [119]
 [120]
 [121]
 [122]
 [123]
 [124]
 [125]
 [126]
 [127]
 [128]
 [129]
 [130]
 [131]
 [132]
 [133]
 [134]
 [135]
 [136]
 [137]
 [138]
 [139]
 [140]
 [141]
 [142]
 [143]
 [144]
 [145]
 [146]
 [147]
 [148]
 [149]] 
 count:118 


In [21]:
#17. Drop rows that contain a missing value from a numpy array created by using iris dataset?
#   Hint: There is no direct function for this hence, select the rows of Iris dataset that does not have any
#   NaN value.

In [22]:
iris_dataset_temp[~np.isnan(iris_dataset_temp).any(axis=1),:]

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [4.6, 3.6, 1. , 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [4.8, 3. , 1.4, 0.3],
       [4.6, 3.2, 1.4, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [5. , 2. , 3.5, 1. ],
       [5. , 2.3, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [23]:
#18. Sort the Admission dataset array based on TOEFL Score column and GRE Score. Use separate code for
#    both.

In [24]:
#GRE score
admission_dataset[admission_dataset[:, 1].argsort(),:]

array([[378.  , 290.  , 100.  , ...,   7.56,   0.  ,   0.47],
       [118.  , 290.  , 104.  , ...,   7.46,   0.  ,   0.45],
       [169.  , 293.  ,  97.  , ...,   7.8 ,   1.  ,   0.64],
       ...,
       [144.  , 340.  , 120.  , ...,   9.92,   1.  ,   0.97],
       [385.  , 340.  , 113.  , ...,   9.74,   1.  ,   0.96],
       [430.  , 340.  , 115.  , ...,   9.06,   1.  ,   0.95]])

In [25]:
#TOEFL score
np.set_printoptions(suppress=True)
admission_dataset[admission_dataset[:, 2].argsort(),:]

array([[369.  , 298.  ,  92.  , ...,   7.88,   0.  ,   0.51],
       [ 29.  , 295.  ,  93.  , ...,   7.2 ,   0.  ,   0.46],
       [ 80.  , 294.  ,  93.  , ...,   7.36,   0.  ,   0.46],
       ...,
       [298.  , 320.  , 120.  , ...,   9.11,   0.  ,   0.86],
       [144.  , 340.  , 120.  , ...,   9.92,   1.  ,   0.97],
       [498.  , 330.  , 120.  , ...,   9.56,   1.  ,   0.93]])

In [26]:
#19. Compute the Euclidean distance between two arrays using Numpy linalg?

In [27]:
p1 = np.array((0, 1, 2))
p2 = np.array((3, 4, 6))

print(np.linalg.norm(p1-p2))

5.830951894845301


In [28]:
#20. Compute and Find the duplicate entries in the given Numpy array and mark them as True. 
#    Create 1-D array

In [29]:


def duplicates(a):
    uniques = np.unique(a)
    result = []
    for i in a:
        if i not in uniques:
            result.append(True)
        else:
            result.append(i)
            uniques = np.delete(uniques, np.where(uniques == i))
    return result


arr=[1,2,3,4,3,2,5,7,8]
print('Array: ', arr)
print(duplicates(arr))


Array:  [1, 2, 3, 4, 3, 2, 5, 7, 8]
[1, 2, 3, 4, True, True, 5, 7, 8]


In [30]:
#21. How to replace all missing values with 0, in a numpy array using Admission.csv and iris.csv?

In [31]:
iris_dataset_temp_0 = np.where(np.isnan(iris_dataset_temp),0,iris_dataset_temp)
iris_dataset_temp_0

array([[0. , 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [0. , 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [0. , 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [0. , 4. , 1.2, 0.2],
       [0. , 4.4, 1.5, 0.4],
       [0. , 3.9, 1.3, 0.4],
       [0. , 3.5, 1.4, 0.3],
       [0. , 3.8, 1.7, 0.3],
       [0. , 3.8, 1.5, 0.3],
       [0. , 3.4, 1.7, 0.2],
       [0. , 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [0. , 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [0. , 3.5, 1.5, 0.2],
       [0. , 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [0. , 3.4, 1.5, 0.4],
       [0. , 4.1, 1.5, 0.1],
       [0. , 4.2, 1.4, 0.2],
       [4.9, 3